export default {
  dimensions: {
    values: [
      'area',
      'base',
      'circumference',
      'count',
      'depth',
      'diameter',
      'height',
      'length',
      'quality',
      'running-time',
      'target',
      'volume',
      'weight',
      'width',
    ],
  },
  measurementUnits: {
    values: [
      'carats',
      'centimeters',
      'cubic-centimeters',
      'feet',
      'inches',
      'kilograms',
      'liters',
      'millimeters',
      'meters',
      'minutes',
      'ounces',
      'percent',
      'pixels',
      'pounds',
      'square-feet',
      'stories',
      'tons',
    ],
  },
};
